'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

export function AuthForm({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const router = useRouter(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); setMessage(''); const supabase=createClient(); const result=mode==='sign-up' ? await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL || `${window.location.origin}/auth/callback`}}) : await supabase.auth.signInWithPassword({email,password}); setBusy(false); if(result.error){setError(result.error.message.includes('confirm')?'Check your email to confirm your account.':'We could not complete that request. Check your details and try again.');return} if(mode==='sign-up' && !result.data.session){setMessage('Check your inbox to confirm your email, then sign in.');return} router.push('/translate'); router.refresh() }
  return <form onSubmit={submit} className="flex flex-col gap-5"><div className="flex flex-col gap-2">{mode==='sign-up'&&<><label htmlFor="name">Full name</label><input id="name" value={name} onChange={e=>setName(e.target.value)} required className="rounded-xl border border-input bg-background px-4 py-3" /></>}<label htmlFor="email">Email address</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required className="rounded-xl border border-input bg-background px-4 py-3" /></div><div className="flex flex-col gap-2"><label htmlFor="password">Password</label><input id="password" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required className="rounded-xl border border-input bg-background px-4 py-3" /></div>{error&&<p role="alert" className="rounded-xl bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p>}{message&&<p role="status" className="rounded-xl bg-primary/10 px-4 py-3 text-sm">{message}</p>}<button disabled={busy} className="min-h-12 rounded-full bg-primary px-5 font-semibold text-primary-foreground disabled:opacity-60">{busy?'Working…':mode==='sign-up'?'Create account':'Sign in'}</button><p className="text-center text-sm text-muted-foreground">{mode==='sign-up'?'Already have an account? ':'New to Perspiq? '}<Link className="font-semibold text-primary underline" href={mode==='sign-up'?'/sign-in':'/sign-up'}>{mode==='sign-up'?'Sign in':'Create an account'}</Link></p></form>
}
