'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { Menu, X, Sparkles, LogIn } from 'lucide-react'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export function SiteHeader() {
  const pathname=usePathname(); const router=useRouter(); const [open,setOpen]=useState(false); const links=[['Translate','/translate'],['History','/history'],['About','/about']]
  async function signOut(){await createClient().auth.signOut();setOpen(false);router.push('/');router.refresh()}
  return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-2 font-semibold tracking-tight" onClick={()=>setOpen(false)}><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles aria-hidden="true" /></span><span>Plainly<span className="text-primary">.</span></span></Link><nav className="hidden items-center gap-7 md:flex" aria-label="Primary navigation">{links.map(([label,href])=><Link key={href} href={href} className={`text-sm font-medium transition-colors hover:text-primary ${pathname===href?'text-primary':'text-muted-foreground'}`}>{label}</Link>)}<Link href="/subscribe" className="rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Go Plus</Link><Link href="/sign-in" className="inline-flex items-center gap-2 text-sm font-semibold"><LogIn aria-hidden="true" /> Sign in</Link></nav><button type="button" className="rounded-lg p-2 md:hidden" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?<X aria-hidden="true" />:<Menu aria-hidden="true" />}</button></div>{open&&<nav className="flex flex-col gap-1 border-t border-border/70 px-5 py-3 md:hidden" aria-label="Mobile navigation">{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)} className="rounded-lg px-3 py-3 font-medium hover:bg-muted">{label}</Link>)}<Link href="/subscribe" onClick={()=>setOpen(false)} className="rounded-lg px-3 py-3 font-semibold text-primary hover:bg-muted">Go Plus</Link><Link href="/sign-in" onClick={()=>setOpen(false)} className="rounded-lg px-3 py-3 font-semibold hover:bg-muted">Sign in</Link></nav>}</header>
}

export function SiteFooter(){return <footer className="border-t border-border/70 bg-muted/40"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-5 py-8 text-sm text-muted-foreground lg:flex-row lg:items-center lg:justify-between lg:px-8"><p className="max-w-2xl leading-6"><strong className="text-foreground">Important:</strong> Plainly explains medical language. It does not diagnose, recommend treatment, or replace professional medical advice.</p><p className="shrink-0">Plainly · Health literacy, made clearer</p></div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <><a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-primary focus:px-4 focus:py-3 focus:text-primary-foreground">Skip to content</a><SiteHeader />{children}<SiteFooter /></>}
export function Disclaimer({dismissible=false}:{dismissible?:boolean}){const [visible,setVisible]=useState(true);if(!visible)return null;return <div role="note" className="flex items-start justify-between gap-4 rounded-2xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm leading-6"><p><strong>Health literacy, not diagnosis.</strong> This tool explains medical language and does not replace professional medical advice.</p>{dismissible&&<button type="button" onClick={()=>setVisible(false)} className="shrink-0 rounded-md p-1 text-muted-foreground hover:bg-background" aria-label="Dismiss disclaimer"><X aria-hidden="true" /></button>}</div>}
export function PageIntro({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <div className="max-w-2xl"><p className="mb-4 text-sm font-semibold uppercase tracking-[.18em] text-primary">{eyebrow}</p><h1 className="text-balance text-4xl font-semibold tracking-tight md:text-5xl">{title}</h1><p className="mt-5 text-pretty text-lg leading-8 text-muted-foreground">{children}</p></div>}
export function StatusBadge({status}:{status:'normal'|'borderline'|'flagged'}){const config={normal:['Normal','✓','bg-emerald-50 text-emerald-800'],borderline:['Borderline','!','bg-amber-50 text-amber-900'],flagged:['Flagged','!','bg-rose-50 text-rose-900']}[status];return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${config[2]}`}><span aria-hidden="true">{config[1]}</span>{config[0]}</span>}
export function EmptyState({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-3xl border border-dashed border-border bg-card px-6 py-16 text-center"><h2 className="text-xl font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-sm leading-6 text-muted-foreground">{children}</p><Link href="/translate" className="mt-6 inline-flex rounded-full bg-primary px-5 py-3 font-semibold text-primary-foreground">Start translating</Link></div>}
export function DemoResults(){return <><ResultCard term="Hemoglobin A1c (HbA1c)" value="6.1%" status="borderline" range="Below 5.7% is typical" meaning="This shows your average blood sugar level over the past 2–3 months." note="A result in this range can be worth discussing with your care team."/><ResultCard term="LDL cholesterol" value="118 mg/dL" status="normal" range="Less than 130 mg/dL" meaning="LDL is sometimes called ‘bad’ cholesterol. Your result is within the general reference range shown here." note="Your clinician may use different targets depending on your overall health history."/><ResultCard term="Vitamin D" value="19 ng/mL" status="flagged" range="30–100 ng/mL" meaning="This measures the amount of vitamin D circulating in your blood." note="Low vitamin D is common and has many possible causes."/></>}
function ResultCard({term,value,status,range,meaning,note}:{term:string;value:string;status:'normal'|'borderline'|'flagged';range:string;meaning:string;note:string}){return <article className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{term}</h3><p className="mt-1 text-2xl font-semibold tracking-tight">{value}</p></div><StatusBadge status={status}/></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="font-medium text-muted-foreground">In plain English</dt><dd className="mt-1 leading-6">{meaning}</dd></div><div><dt className="font-medium text-muted-foreground">Reference range</dt><dd className="mt-1 leading-6">{range}</dd></div></dl><div className="mt-5 rounded-xl bg-muted/70 p-3 text-sm leading-6"><strong>Why this matters: </strong>{note}</div></article>}
export { ResultCard }
